apiVersion: v1
kind: Pod
metadata:
  name: q2-nginx-pod
  label:
    app: nginx-q2-app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
