apiVersion: v1
kind: Pod
metadata:
  name: q7-nginx-pod
  labels:
    app: nginx-app-q7
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "300m"
        limits:
          memory: "256Mi"
          cpu: "700m"
